"""PDF report generation for patient predictions."""

import io
from datetime import datetime

from fpdf import FPDF


class PatientReport(FPDF):
    """Custom PDF report for patient risk assessment."""

    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.cell(0, 10, "BanglaHealth-AI", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "", 10)
        self.cell(0, 6, "Patient Risk Assessment Report", new_x="LMARGIN", new_y="NEXT", align="C")
        self.line(10, self.get_y() + 2, 200, self.get_y() + 2)
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Generated by BanglaHealth-AI | {datetime.now().strftime('%Y-%m-%d %H:%M')}", align="C")


def generate_patient_pdf(
    patient_data: dict,
    risk_level: str,
    confidence: dict,
    alerts: list[dict],
    dataset_type: str = "diabetes",
    shap_values: dict | None = None,
) -> bytes:
    """Generate a PDF report for a patient prediction.

    Args:
        patient_data: Dict of feature_name -> value.
        risk_level: "Low", "Medium", or "High".
        confidence: Dict with Low/Medium/High probabilities.
        alerts: List of clinical alert dicts.
        dataset_type: "diabetes" or "heart".
        shap_values: Optional dict of feature_name -> SHAP value.

    Returns:
        PDF file as bytes.
    """
    pdf = PatientReport()
    pdf.add_page()

    # Report metadata
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Date: {datetime.now().strftime('%B %d, %Y')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 6, f"Disease Type: {dataset_type.title()}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    # Risk Level
    pdf.set_font("Helvetica", "B", 14)
    color_map = {"Low": (40, 167, 69), "Medium": (255, 193, 7), "High": (220, 53, 69)}
    r, g, b = color_map.get(risk_level, (108, 117, 125))
    pdf.set_text_color(r, g, b)
    pdf.cell(0, 10, f"Risk Level: {risk_level}", new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)

    # Confidence scores
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Confidence — Low: {confidence.get('Low', 0):.1%} | Medium: {confidence.get('Medium', 0):.1%} | High: {confidence.get('High', 0):.1%}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Patient Data
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Patient Data", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)

    col_width = 90
    for i, (key, value) in enumerate(patient_data.items()):
        if isinstance(value, float):
            text = f"{key}: {value:.2f}"
        else:
            text = f"{key}: {value}"

        if i % 2 == 0:
            pdf.cell(col_width, 6, text)
        else:
            pdf.cell(col_width, 6, text, new_x="LMARGIN", new_y="NEXT")

    if len(patient_data) % 2 != 0:
        pdf.ln(6)
    pdf.ln(4)

    # Clinical Alerts
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Clinical Findings", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)

    for alert in alerts:
        severity = alert.get("severity", "normal")
        message = alert.get("message", "")
        feature = alert.get("feature", "")

        if severity == "high":
            pdf.set_text_color(220, 53, 69)
            prefix = "[!] "
        else:
            pdf.set_text_color(40, 167, 69)
            prefix = "[OK] "

        pdf.multi_cell(0, 6, f"{prefix}{feature}: {message}")

    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # SHAP Values (if available)
    if shap_values:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Feature Impact (SHAP Values)", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)

        sorted_shap = sorted(shap_values.items(), key=lambda x: abs(x[1]), reverse=True)
        for feat, val in sorted_shap:
            direction = "increases" if val > 0 else "decreases"
            pdf.cell(0, 5, f"  {feat}: {val:+.4f} ({direction} risk)", new_x="LMARGIN", new_y="NEXT")

        pdf.ln(4)

    # Disclaimer
    pdf.ln(6)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.multi_cell(0, 4,
        "DISCLAIMER: This report is generated by an AI model for research purposes only. "
        "It is NOT a medical diagnosis. Always consult a qualified healthcare professional "
        "for medical decisions. The predictions are based on limited public datasets and "
        "should not be used for clinical decision-making without proper validation."
    )

    # Return as bytes
    return pdf.output()
